name: Alerta Meteorológica Automática

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  ejecutar-alerta:
    runs-on: ubuntu-latest
    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-lxml python3-pip unzip
          pip install requests beautifulsoup4 shapely folium selenium lxml

      - name: Instalar Google Chrome y ChromeDriver
        uses: browser-actions/setup-chrome@v1

      - name: Ejecutar script
        run: python $GITHUB_WORKSPACE/alertas_smn.py


