name: Alerta Meteorológica Automática

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  ejecutar-alerta:
    runs-on: ubuntu-latest
    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip python3-lxml python3-pip chromium
          pip install requests beautifulsoup4 shapely folium selenium undetected-chromedriver lxml

      - name: Instalar ChromeDriver 135
        run: |
          wget -q https://edgedl.me.gvt1.com/edgedl/chrome/chromedriver/135.0.7049.0/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Ejecutar script
        run: python $GITHUB_WORKSPACE/alertas_smn.py
