name: Alerta Meteorológica Automática

on:
  schedule:
    - cron: '0 */2 * * *'  # Cada 2 horas
  workflow_dispatch:

jobs:
  ejecutar-alerta:
    runs-on: ubuntu-latest
    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium
          pip install requests beautifulsoup4 shapely folium selenium webdriver-manager lxml

      - name: Ejecutar script de alerta
        run: python $GITHUB_WORKSPACE/alertas_smn.py

