name: Alerta Meteorológica Automática

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ejecutar-alerta:
    runs-on: ubuntu-latest
    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip python3-lxml python3-pip chromium
          pip install requests beautifulsoup4 shapely folium selenium undetected-chromedriver lxml

      - name: Ejecutar script
        run: python alertas_smn.py
        