name: Alerta Meteorológica Automática

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  ejecutar-alerta:
    runs-on: ubuntu-latest
    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar dependencias Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-lxml
          pip install requests beautifulsoup4 shapely folium selenium webdriver-manager lxml

      - name: Instalar Chrome y ChromeDriver compatibles
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable    # instala Chrome estable
          driver-version: stable    # instala el ChromeDriver que coincide

      - name: Ejecutar script de alertas
        run: python $GITHUB_WORKSPACE/alertas_smn.py



