name: Alerta Meteorológica Automática

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  alerta-meteorologica:
    runs-on: ubuntu-latest
    env:
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Google Chrome y ChromeDriver compatibles
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip python3-lxml python3-pip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb || sudo apt --fix-broken install -y
          CHROME_BIN=$(which google-chrome)
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*}")
          wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
          unzip -o /tmp/chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          pip install requests beautifulsoup4 shapely folium selenium lxml

      - name: Ejecutar verificador de alertas
        run: |
          python <<EOF
          # Aquí iría todo tu script principal (omitido por brevedad en esta vista)
          # con Selenium incluido para capturar mapa como PNG y enviarlo por correo
          print("Script ejecutado correctamente")
          EOF

